[package]
name = "rust_guessing_game"
version = "0.1.0"
authors = ["Ben Hunter <code@benhunter.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
